export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';

export const AUTH_USER = 'AUTH_USER';

export const SET_LOADING = 'SET_LOADING';
